#!/bin/bash
#sbatch sentinel.sbatch /data/sentinel/114/114-08/
# sbatch sentinel.sbatch /data/sentinel/114/114-09/
#sbatch sentinel.sbatch /data/sentinel/114/114-10/
#sbatch sentinel.sbatch /data/sentinel/114/114-11/
#sbatch sentinel.sbatch /data/sentinel/114/114-12/
#sbatch sentinel.sbatch /data/sentinel/114/114-13/
#sbatch sentinel.sbatch /data/sentinel/114/114-14/
#sbatch sentinel.sbatch /data/sentinel/114/114-15/


# 41
#sbatch sentinel.sbatch /work/yxtang/zlc/sentinel/158/158-06/
#sbatch sentinel.sbatch /work/yxtang/zlc/sentinel/158/158-07/
#sbatch sentinel.sbatch /work/yxtang/zlc/sentinel/158/158-08/
#sbatch sentinel.sbatch /work/yxtang/zlc/sentinel/158/158-09/
#sbatch sentinel.sbatch /work/yxtang/zlc/sentinel/158/158-10/
#sbatch sentinel.sbatch /work/yxtang/zlc/sentinel/129/129-02/
sbatch sentinel.sbatch /work/yxtang/zlc/sentinel/128/128-03/
sbatch sentinel.sbatch /work/yxtang/zlc/sentinel/128/128-04/
sbatch sentinel.sbatch /work/yxtang/zlc/sentinel/128/128-05/
sbatch sentinel.sbatch /work/yxtang/zlc/sentinel/128/128-06/
sbatch sentinel.sbatch /work/yxtang/zlc/sentinel/128/128-07/
#sbatch sentinel.sbatch /work/yxtang/zlc/sentinel/143/143-10/
#sbatch sentinel.sbatch /work/yxtang/zlc/sentinel/143/143-11/
#sbatch sentinel.sbatch /work/yxtang/zlc/sentinel/143/143-12/
#sbatch sentinel.sbatch /work/yxtang/zlc/sentinel/143/143-13/
#sbatch sentinel.sbatch /work/yxtang/zlc/sentinel/143/143-14/

#sbatch sentinel.sbatch /data/sentinel/27/27-02/
#sbatch sentinel.sbatch /data/sentinel/27/27-03/
#sbatch sentinel.sbatch /data/sentinel/172/172-07/
#sbatch sentinel.sbatch /data/sentinel/172/172-08/
#sbatch sentinel.sbatch /data/sentinel/172/172-09/
#sbatch sentinel.sbatch /data/sentinel/172/172-10/
#sbatch sentinel.sbatch /data/sentinel/172/172-11/
#sbatch sentinel.sbatch /data/sentinel/172/172-12/
